// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoLxqrD4xCgaC068hZSx7T2s0k_uoRD8E',
    appId: '1:483216805812:web:a00870ade40ec277e72ce1',
    messagingSenderId: '483216805812',
    projectId: 'parresia-c9cb6',
    authDomain: 'parresia-c9cb6.firebaseapp.com',
    storageBucket: 'parresia-c9cb6.firebasestorage.app',
    measurementId: 'G-3SR1QQN7F0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAvbfgYgY-B0A6Q4qFpRafut5IzQeMYU0',
    appId: '1:483216805812:android:b560369c8168397ee72ce1',
    messagingSenderId: '483216805812',
    projectId: 'parresia-c9cb6',
    storageBucket: 'parresia-c9cb6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7RRity7b02m9y52w08JMCV6G2LMyh05M',
    appId: '1:483216805812:ios:4c9a22e3eb4fa412e72ce1',
    messagingSenderId: '483216805812',
    projectId: 'parresia-c9cb6',
    storageBucket: 'parresia-c9cb6.firebasestorage.app',
    iosBundleId: 'com.futureway.kergymaToEternity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7RRity7b02m9y52w08JMCV6G2LMyh05M',
    appId: '1:483216805812:ios:4c9a22e3eb4fa412e72ce1',
    messagingSenderId: '483216805812',
    projectId: 'parresia-c9cb6',
    storageBucket: 'parresia-c9cb6.firebasestorage.app',
    iosBundleId: 'com.futureway.kergymaToEternity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoLxqrD4xCgaC068hZSx7T2s0k_uoRD8E',
    appId: '1:483216805812:web:e362475d7e617595e72ce1',
    messagingSenderId: '483216805812',
    projectId: 'parresia-c9cb6',
    authDomain: 'parresia-c9cb6.firebaseapp.com',
    storageBucket: 'parresia-c9cb6.firebasestorage.app',
    measurementId: 'G-SJB0J9QRF2',
  );

}